# Generated by Django 3.1.7 on 2021-05-11 02:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticker', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Stock2',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('symbol', models.CharField(default='', max_length=50, verbose_name='Symbol')),
                ('company', models.CharField(default='Other company', max_length=50, verbose_name='Company')),
            ],
        ),
        migrations.CreateModel(
            name='PredictPrice',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='timestamp_symbol')),
                ('price', models.DecimalField(decimal_places=2, default=None, max_digits=11, verbose_name='Price')),
                ('date', models.DateTimeField(default=None, verbose_name='Date')),
                ('model_type', models.CharField(default=None, max_length=20, verbose_name='model_type')),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_set', to='quotes.stock2')),
            ],
        ),
    ]
